import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAccount } from "@/hooks/use-account";
import { useLocale } from "@/lib/locale-provider";
import { trpc } from "@/lib/trpc";

export default function SearchScreen() {
  const router = useRouter();
  const { isAuthenticated } = useAccount();
  const { isArabic, direction } = useLocale();
  const [input, setInput] = useState("");
  const [term, setTerm] = useState("");
  useEffect(() => { const timer = setTimeout(() => setTerm(input.trim().length >= 2 ? input.trim() : ""), 300); return () => clearTimeout(timer); }, [input]);
  const query = trpc.search.records.useQuery({ term: term || "--" }, { enabled: isAuthenticated && term.length >= 2 });
  const text = isArabic ? { title: "بحث شامل", subtitle: "ابحث ضمن السجلات التي تملك صلاحية الوصول إليها", placeholder: "رقم الطلب، رقم المعاملة، العنوان أو الجوال", results: "نتائج البحث", requests: "الطلبات", transactions: "المعاملات", empty: "اكتب كلمتين على الأقل لبدء البحث.", noResults: "لا توجد نتائج متاحة ضمن صلاحياتك.", signIn: "سجّل الدخول لاستخدام البحث المحمي." } : { title: "Global search", subtitle: "Search records you are permitted to access", placeholder: "Request number, transaction number, title or phone", results: "Search results", requests: "Requests", transactions: "Transactions", empty: "Type at least two characters to start searching.", noResults: "No results are available within your permissions.", signIn: "Sign in to use protected search." };
  const hasResults = Boolean(query.data && (query.data.requests.length || query.data.transactions.length));
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.container}>
    <View style={[styles.header, { flexDirection: isArabic ? "row-reverse" : "row" }]}><Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={22} color="#17382F" /></Pressable><View style={styles.headerCopy}><Text style={[styles.title, { writingDirection: direction }]}>{text.title}</Text><Text style={[styles.subtitle, { writingDirection: direction }]}>{text.subtitle}</Text></View></View>
    {!isAuthenticated ? <Pressable onPress={() => router.push("/account" as never)} style={styles.empty}><Ionicons name="lock-closed-outline" size={31} color="#0B5D45" /><Text style={[styles.emptyText, { writingDirection: direction }]}>{text.signIn}</Text></Pressable> : <><View style={[styles.searchBox, { flexDirection: isArabic ? "row-reverse" : "row" }]}><Ionicons name="search-outline" size={20} color="#66756E" /><TextInput value={input} onChangeText={setInput} placeholder={text.placeholder} placeholderTextColor="#93A39C" style={[styles.searchInput, { writingDirection: direction, textAlign: isArabic ? "right" : "left" }]} autoFocus /></View>{query.isLoading && <ActivityIndicator color="#0B5D45" style={styles.loading} />}{!term && <View style={styles.empty}><Ionicons name="search-outline" size={32} color="#78A190" /><Text style={[styles.emptyText, { writingDirection: direction }]}>{text.empty}</Text></View>}{term && !query.isLoading && !hasResults && <View style={styles.empty}><Ionicons name="folder-open-outline" size={32} color="#78A190" /><Text style={[styles.emptyText, { writingDirection: direction }]}>{text.noResults}</Text></View>}{hasResults && <ScrollView contentContainerStyle={styles.results}><Text style={[styles.sectionTitle, { writingDirection: direction }]}>{text.results}</Text>{query.data?.requests.length ? <><Text style={[styles.groupTitle, { writingDirection: direction }]}>{text.requests}</Text>{query.data.requests.map((item) => <View key={`request-${item.id}`} style={[styles.card, { flexDirection: isArabic ? "row-reverse" : "row" }]}><View style={styles.icon}><Ionicons name="document-text-outline" size={19} color="#0B5D45" /></View><View style={styles.copy}><Text style={[styles.cardTitle, { writingDirection: direction }]}>{item.number}</Text><Text style={[styles.cardBody, { writingDirection: direction }]}>{item.title}</Text></View></View>)}</> : null}{query.data?.transactions.length ? <><Text style={[styles.groupTitle, { writingDirection: direction }]}>{text.transactions}</Text>{query.data.transactions.map((item) => <Pressable key={`transaction-${item.id}`} onPress={() => router.push(`/transaction/${item.id}` as never)} style={({ pressed }) => [styles.card, { flexDirection: isArabic ? "row-reverse" : "row" }, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name="folder-open-outline" size={19} color="#0B5D45" /></View><View style={styles.copy}><Text style={[styles.cardTitle, { writingDirection: direction }]}>{item.number || `#${item.id}`}</Text><Text style={[styles.cardBody, { writingDirection: direction }]}>{item.nextAction || item.status}</Text></View></Pressable>)}</> : null}</ScrollView>}</>}
  </View></ScreenContainer>;
}

const styles = StyleSheet.create({ container: { flex: 1, padding: 20 }, header: { alignItems: "center", gap: 12 }, close: { alignItems: "center", backgroundColor: "#F0F4F0", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, headerCopy: { alignItems: "flex-end", flex: 1 }, title: { color: "#17382F", fontSize: 22, fontWeight: "800", textAlign: "right" }, subtitle: { color: "#66756E", fontSize: 12, marginTop: 4, textAlign: "right" }, searchBox: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#DCE7DE", borderRadius: 14, borderWidth: 1, gap: 9, marginTop: 22, minHeight: 53, paddingHorizontal: 13 }, searchInput: { color: "#17382F", flex: 1, fontSize: 14 }, loading: { marginTop: 28 }, results: { gap: 9, paddingBottom: 30, paddingTop: 20 }, sectionTitle: { color: "#344D42", fontSize: 15, fontWeight: "800", textAlign: "right" }, groupTitle: { color: "#66756E", fontSize: 12, fontWeight: "800", marginTop: 8, textAlign: "right" }, card: { alignItems: "flex-start", backgroundColor: "#FFFFFF", borderColor: "#E1E9E3", borderRadius: 15, borderWidth: 1, gap: 10, padding: 13 }, icon: { alignItems: "center", backgroundColor: "#E9F5EC", borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, copy: { alignItems: "flex-end", flex: 1 }, cardTitle: { color: "#17382F", fontSize: 13, fontWeight: "800", textAlign: "right" }, cardBody: { color: "#66756E", fontSize: 11, lineHeight: 17, marginTop: 4, textAlign: "right" }, empty: { alignItems: "center", backgroundColor: "#F7FAF8", borderColor: "#E1E9E3", borderRadius: 18, borderStyle: "dashed", borderWidth: 1, marginTop: 24, padding: 28 }, emptyText: { color: "#66756E", fontSize: 13, lineHeight: 20, marginTop: 8, textAlign: "center" }, pressed: { opacity: 0.7 } });
