import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, View } from "react-native";
import { AppText as Text } from "@/components/ui/app-text";
import { ScreenContainer } from "@/components/screen-container";
import { useAccount } from "@/hooks/use-account";
import { trpc } from "@/lib/trpc";

export default function NotificationPreferencesScreen() {
  const router = useRouter();
  const { isAuthenticated } = useAccount();
  const preferences = trpc.notificationPreferences.get.useQuery(undefined, { enabled: isAuthenticated });
  const logs = trpc.notificationPreferences.deliveryLog.useQuery(undefined, { enabled: isAuthenticated });
  const update = trpc.notificationPreferences.update.useMutation({ onSuccess: () => { void preferences.refetch(); void logs.refetch(); } });
  if (!isAuthenticated) return <ScreenContainer style={styles.state}><Text style={styles.stateText}>سجّل الدخول لإدارة تفضيلات الإشعارات.</Text></ScreenContainer>;
  if (!preferences.data) return <ScreenContainer style={styles.state}><ActivityIndicator color="#0B5D45" /></ScreenContainer>;
  const value = preferences.data;
  const patch = (next: Partial<typeof value>) => update.mutate({ inAppEnabled: next.inAppEnabled ?? value.inAppEnabled, digestFrequency: next.digestFrequency ?? value.digestFrequency, quietHoursEnabled: next.quietHoursEnabled ?? value.quietHoursEnabled, quietStartHour: next.quietStartHour ?? value.quietStartHour, quietEndHour: next.quietEndHour ?? value.quietEndHour });
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={22} color="#17382F" /></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>أبو مشعل · الإشعارات</Text><Text style={styles.title}>تفضيلات الاستلام</Text></View></View><Setting label="إظهار الإشعارات داخل التطبيق" description="تحفظ السجلات دائماً ضمن الحساب للمراجعة." value={value.inAppEnabled} onChange={(inAppEnabled) => patch({ inAppEnabled })} /><Setting label="تجميع يومي للإشعارات العادية" description="رسائل الدعم والتحويل البشري تبقى فورية." value={value.digestFrequency === "daily"} onChange={(daily) => patch({ digestFrequency: daily ? "daily" : "immediate" })} /><Setting label="ساعات هدوء" description="تُحفظ التنبيهات العادية وتظهر لاحقاً في مركز الإشعارات." value={value.quietHoursEnabled} onChange={(quietHoursEnabled) => patch({ quietHoursEnabled })} /><Text style={styles.section}>آخر قرارات التسليم</Text>{logs.data?.length ? logs.data.slice(0, 10).map((log) => <View key={log.id} style={styles.log}><View style={styles.logCopy}><Text style={styles.logTitle}>{log.title}</Text><Text style={styles.logMeta}>{labelDelivery(log.status)} · {new Date(log.createdAt).toLocaleString("ar-SA")}</Text></View><Ionicons name={log.status === "delivered" ? "checkmark-circle-outline" : log.status === "suppressed" ? "moon-outline" : "time-outline"} size={19} color="#0B5D45" /></View>) : <Text style={styles.empty}>لا توجد سجلات تسليم بعد.</Text>}{update.isPending ? <ActivityIndicator color="#0B5D45" style={styles.saving} /> : null}</ScrollView></ScreenContainer>;
}
function Setting({ label, description, value, onChange }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.setting}><View style={styles.settingCopy}><Text style={styles.settingTitle}>{label}</Text><Text style={styles.settingDescription}>{description}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: "#DCE7DE", true: "#8EC9A2" }} thumbColor={value ? "#0B5D45" : "#FFFFFF"} /></View>; }
function labelDelivery(status: string) { return ({ delivered: "تم التسليم", queued: "مجمّع", suppressed: "مؤجل", failed: "تعذر" } as Record<string, string>)[status] ?? status; }
const styles = StyleSheet.create({ container: { padding: 20, paddingBottom: 48 }, header: { alignItems: "center", flexDirection: "row-reverse", gap: 12 }, close: { alignItems: "center", backgroundColor: "#F0F4F0", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, headerCopy: { alignItems: "flex-end", flex: 1 }, eyebrow: { color: "#0B5D45", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, title: { color: "#17382F", fontSize: 21, fontWeight: "900", marginTop: 3, writingDirection: "rtl" }, setting: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#DCE7DE", borderRadius: 15, borderWidth: 1, flexDirection: "row-reverse", gap: 10, marginTop: 14, padding: 13 }, settingCopy: { alignItems: "flex-end", flex: 1 }, settingTitle: { color: "#17382F", fontSize: 13, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, settingDescription: { color: "#66756E", fontSize: 10, lineHeight: 16, marginTop: 4, textAlign: "right", writingDirection: "rtl" }, section: { color: "#344D42", fontSize: 15, fontWeight: "900", marginTop: 24, textAlign: "right", writingDirection: "rtl" }, log: { alignItems: "flex-start", backgroundColor: "#F7FAF8", borderColor: "#E1E9E3", borderRadius: 13, borderWidth: 1, flexDirection: "row-reverse", gap: 8, marginTop: 8, padding: 11 }, logCopy: { alignItems: "flex-end", flex: 1 }, logTitle: { color: "#25463A", fontSize: 12, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, logMeta: { color: "#74877D", fontSize: 9, marginTop: 3, textAlign: "right", writingDirection: "rtl" }, empty: { color: "#66756E", fontSize: 12, marginTop: 10, textAlign: "right", writingDirection: "rtl" }, state: { alignItems: "center", flex: 1, justifyContent: "center" }, stateText: { color: "#66756E", fontSize: 13, writingDirection: "rtl" }, saving: { marginTop: 15 } });
