import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAccount } from "@/hooks/use-account";
import { useLocale } from "@/lib/locale-provider";
import { trpc } from "@/lib/trpc";

export default function KnowledgeScreen() {
  const router = useRouter();
  const { account, isAuthenticated } = useAccount();
  const { locale, isArabic, direction } = useLocale();
  const [showComposer, setShowComposer] = useState(false);
  const [kind, setKind] = useState<"article" | "faq">("article");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [source, setSource] = useState("");
  const knowledge = trpc.knowledge.list.useQuery({ language: locale }, { enabled: isAuthenticated });
  const createArticle = trpc.knowledge.createArticle.useMutation({ onSuccess: () => { setTitle(""); setContent(""); setSource(""); setShowComposer(false); void knowledge.refetch(); } });
  const createFaq = trpc.knowledge.createFaq.useMutation({ onSuccess: () => { setTitle(""); setContent(""); setShowComposer(false); void knowledge.refetch(); } });
  const isManager = account?.role === "supervisor" || account?.role === "admin" || account?.role === "super_admin";
  const text = isArabic ? { title: "مركز المعرفة", subtitle: "معلومات إرشادية معتمدة لمتابعة طلبك", add: "إضافة محتوى", article: "مقال", faq: "سؤال شائع", subject: "العنوان أو السؤال", content: "المحتوى أو الإجابة", source: "اسم المصدر (اختياري)", save: "نشر", empty: "لا توجد مواد معرفة منشورة بهذه اللغة حالياً.", disclaimer: "المحتوى إرشادي. أبو مشعل منصة مستقلة ولا يمثل أي جهة حكومية." } : { title: "Knowledge Center", subtitle: "Approved guidance for tracking your request", add: "Add content", article: "Article", faq: "FAQ", subject: "Title or question", content: "Content or answer", source: "Source label (optional)", save: "Publish", empty: "No published knowledge items in this language yet.", disclaimer: "This content is informational. Abu Mishal is independent and does not represent a government entity." };
  const save = async () => { if (title.trim().length < 3 || content.trim().length < 3) { Alert.alert(isArabic ? "أكمل الحقول" : "Complete the fields", isArabic ? "أدخل عنواناً ومحتوى صالحين." : "Enter a valid title and content."); return; } try { if (kind === "article") await createArticle.mutateAsync({ title: title.trim(), content: content.trim(), language: locale, sourceLabel: source.trim() || undefined }); else await createFaq.mutateAsync({ question: title.trim(), answer: content.trim(), language: locale }); } catch { Alert.alert(isArabic ? "تعذر النشر" : "Publishing failed", isArabic ? "تحقق من الصلاحيات وحاول مرة أخرى." : "Check your permissions and try again."); } };
  const data = [...(knowledge.data?.articles ?? []).map((item) => ({ ...item, kind: "article" as const })), ...(knowledge.data?.faqs ?? []).map((item) => ({ ...item, kind: "faq" as const }))];
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.container}>
    <View style={[styles.header, { flexDirection: isArabic ? "row-reverse" : "row" }]}><Pressable onPress={() => router.back()} style={styles.close}><Ionicons name="close" size={22} color="#17382F" /></Pressable><View style={styles.headerCopy}><Text style={[styles.title, { writingDirection: direction }]}>{text.title}</Text><Text style={[styles.subtitle, { writingDirection: direction }]}>{text.subtitle}</Text></View></View>
    <View style={styles.disclaimer}><Ionicons name="information-circle-outline" size={18} color="#49665B" /><Text style={[styles.disclaimerText, { writingDirection: direction }]}>{text.disclaimer}</Text></View>
    {isManager && <Pressable onPress={() => setShowComposer((value) => !value)} style={styles.addButton}><Ionicons name="add" size={18} color="#FFFFFF" /><Text style={[styles.addText, { writingDirection: direction }]}>{text.add}</Text></Pressable>}
    {showComposer && <View style={styles.composer}><View style={[styles.kindRow, { flexDirection: isArabic ? "row-reverse" : "row" }]}>{(["article", "faq"] as const).map((value) => <Pressable key={value} onPress={() => setKind(value)} style={[styles.kind, kind === value && styles.kindActive]}><Text style={[styles.kindText, kind === value && styles.kindTextActive, { writingDirection: direction }]}>{value === "article" ? text.article : text.faq}</Text></Pressable>)}</View><TextInput value={title} onChangeText={setTitle} placeholder={text.subject} placeholderTextColor="#93A39C" style={[styles.input, { writingDirection: direction, textAlign: isArabic ? "right" : "left" }]} /><TextInput value={content} onChangeText={setContent} multiline placeholder={text.content} placeholderTextColor="#93A39C" style={[styles.input, styles.contentInput, { writingDirection: direction, textAlign: isArabic ? "right" : "left" }]} />{kind === "article" && <TextInput value={source} onChangeText={setSource} placeholder={text.source} placeholderTextColor="#93A39C" style={[styles.input, { writingDirection: direction, textAlign: isArabic ? "right" : "left" }]} />}<Pressable onPress={() => void save()} style={styles.saveButton}><Text style={[styles.saveText, { writingDirection: direction }]}>{text.save}</Text></Pressable></View>}
    {!isAuthenticated ? <Pressable onPress={() => router.push("/account" as never)} style={styles.empty}><Ionicons name="lock-closed-outline" size={30} color="#0B5D45" /><Text style={[styles.emptyText, { writingDirection: direction }]}>{isArabic ? "سجّل الدخول للوصول إلى مركز المعرفة." : "Sign in to access the knowledge center."}</Text></Pressable> : knowledge.isLoading ? <ActivityIndicator color="#0B5D45" style={styles.loading} /> : <FlatList data={data} keyExtractor={(item) => `${item.kind}-${item.id}`} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Ionicons name="book-outline" size={32} color="#78A190" /><Text style={[styles.emptyText, { writingDirection: direction }]}>{text.empty}</Text></View>} renderItem={({ item }) => <View style={styles.card}><View style={[styles.cardTop, { flexDirection: isArabic ? "row-reverse" : "row" }]}><Text style={[styles.badge, { writingDirection: direction }]}>{item.kind === "article" ? text.article : text.faq}</Text><Text style={[styles.cardTitle, { writingDirection: direction }]}>{item.kind === "article" ? item.title : item.question}</Text></View><Text style={[styles.cardBody, { writingDirection: direction }]}>{item.kind === "article" ? (item.excerpt || item.content) : item.answer}</Text>{item.kind === "article" && item.sourceLabel && <Text style={[styles.source, { writingDirection: direction }]}>{isArabic ? "المصدر: " : "Source: "}{item.sourceLabel}</Text>}<Text style={[styles.updated, { writingDirection: direction }]}>{isArabic ? "آخر تحديث: " : "Updated: "}{new Date(item.updatedAt).toLocaleDateString(isArabic ? "ar-SA" : "en-US")}</Text></View>} />}
  </View></ScreenContainer>;
}

const styles = StyleSheet.create({ container: { flex: 1, padding: 20 }, header: { alignItems: "center", gap: 12 }, close: { alignItems: "center", backgroundColor: "#F0F4F0", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, headerCopy: { alignItems: "flex-end", flex: 1 }, title: { color: "#17382F", fontSize: 22, fontWeight: "800", textAlign: "right" }, subtitle: { color: "#66756E", fontSize: 12, marginTop: 4, textAlign: "right" }, disclaimer: { alignItems: "flex-start", backgroundColor: "#F4F0E6", borderColor: "#E7D9BD", borderRadius: 14, borderWidth: 1, flexDirection: "row-reverse", gap: 8, marginTop: 18, padding: 12 }, disclaimerText: { color: "#49665B", flex: 1, fontSize: 11, lineHeight: 17, textAlign: "right" }, addButton: { alignItems: "center", alignSelf: "flex-end", backgroundColor: "#0B5D45", borderRadius: 12, flexDirection: "row-reverse", gap: 5, marginTop: 12, paddingHorizontal: 12, paddingVertical: 9 }, addText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, composer: { backgroundColor: "#F7FAF8", borderColor: "#DCE7DE", borderRadius: 16, borderWidth: 1, gap: 9, marginTop: 12, padding: 12 }, kindRow: { gap: 8 }, kind: { borderColor: "#CFE1D4", borderRadius: 999, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, kindActive: { backgroundColor: "#0B5D45", borderColor: "#0B5D45" }, kindText: { color: "#49665B", fontSize: 11, fontWeight: "800" }, kindTextActive: { color: "#FFFFFF" }, input: { backgroundColor: "#FFFFFF", borderColor: "#DCE7DE", borderRadius: 11, borderWidth: 1, color: "#17382F", minHeight: 45, paddingHorizontal: 11 }, contentInput: { minHeight: 90, paddingTop: 10, textAlignVertical: "top" }, saveButton: { alignItems: "center", backgroundColor: "#0B5D45", borderRadius: 11, minHeight: 43, justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, loading: { marginTop: 40 }, list: { gap: 10, paddingTop: 16, paddingBottom: 30 }, card: { backgroundColor: "#FFFFFF", borderColor: "#E1E9E3", borderRadius: 16, borderWidth: 1, padding: 14 }, cardTop: { alignItems: "center", gap: 8, justifyContent: "space-between" }, badge: { backgroundColor: "#E9F5EC", color: "#0B5D45", fontSize: 10, fontWeight: "800", paddingHorizontal: 8, paddingVertical: 4 }, cardTitle: { color: "#17382F", flex: 1, fontSize: 14, fontWeight: "800", textAlign: "right" }, cardBody: { color: "#5A6D63", fontSize: 12, lineHeight: 19, marginTop: 9, textAlign: "right" }, source: { color: "#0B5D45", fontSize: 11, fontWeight: "700", marginTop: 9, textAlign: "right" }, updated: { color: "#8B9B93", fontSize: 10, marginTop: 6, textAlign: "right" }, empty: { alignItems: "center", backgroundColor: "#F7FAF8", borderColor: "#E1E9E3", borderRadius: 18, borderStyle: "dashed", borderWidth: 1, marginTop: 22, padding: 28 }, emptyText: { color: "#66756E", fontSize: 13, lineHeight: 20, marginTop: 8, textAlign: "center" } });
