import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { AppRole, useAppRole } from "@/lib/role-provider";
import { useAccount } from "@/hooks/use-account";
import { getReminderPermissionStatus, ReminderPermissionState, requestReminderPermission } from "@/lib/notification-service";
import { useLocale } from "@/lib/locale-provider";

const roles: { value: AppRole; label: string }[] = [{ value: "customer", label: "عميل" }, { value: "employee", label: "موظف" }, { value: "supervisor", label: "مشرف" }];

export default function SettingsScreen() {
  const router = useRouter();
  const { role, setRole } = useAppRole();
  const { isAuthenticated, user, account } = useAccount();
  const { locale, setLocale } = useLocale();
  const [permission, setPermission] = useState<ReminderPermissionState>("unsupported");
  useEffect(() => { void getReminderPermissionStatus().then(setPermission); }, []);
  async function enableReminders() { const granted = await requestReminderPermission(); setPermission(granted ? "granted" : "denied"); }
  const reminderMessage = permission === "granted" ? "الإشعارات مفعّلة. ستظهر التذكيرات التي تحفظها مستقبلاً." : permission === "denied" ? "لم تمنح الإذن بعد. يمكنك طلبه مرة أخرى أو تفعيله من إعدادات الجهاز." : "تعمل التنبيهات المحلية على هاتفك بعد تثبيت التطبيق.";
  return <ScreenContainer style={styles.container}>
    <View style={styles.header}><Text style={styles.title}>الإعدادات</Text><Text style={styles.subtitle}>خيارات وخصوصية أبو مشعل</Text></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>الحساب</Text><Pressable onPress={() => router.push("/account" as never)} style={({ pressed }) => [styles.accountCard, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name={isAuthenticated ? "cloud-done-outline" : "person-add-outline"} color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{isAuthenticated ? (user?.name || "تم تسجيل الدخول") : "تسجيل الدخول للمزامنة"}</Text><Text style={styles.cardBody}>{isAuthenticated ? "حسابك متصل. تُستخدم صلاحياته الفعلية للمزامنة." : "سجّل الدخول لحفظ بياناتك ومزامنتها بين الأجهزة."}</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable></View>
    {isAuthenticated && (account?.role === "admin" || account?.role === "super_admin") && <View style={styles.section}><Text style={styles.sectionTitle}>إدارة النظام</Text><Pressable onPress={() => router.push("/admin" as never)} style={({ pressed }) => [styles.accountCard, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="speedometer-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>لوحة متابعة المعاملات</Text><Text style={styles.cardBody}>عرض مؤشرات النظام وجميع المعاملات ضمن صلاحيات المدير.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable></View>}
    <View style={styles.section}><Text style={styles.sectionTitle}>المساعدة والمعرفة</Text><Pressable onPress={() => router.push("/assistant" as never)} style={({ pressed }) => [styles.accountCard, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="sparkles-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>مساعد أبو مشعل</Text><Text style={styles.cardBody}>اسأل عن المتابعة والمتطلبات من مصادر المعرفة المنشورة.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable><Pressable onPress={() => router.push("/search" as never)} style={({ pressed }) => [styles.accountCard, { marginTop: 10 }, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="search-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>بحث شامل</Text><Text style={styles.cardBody}>ابحث ضمن الطلبات والمعاملات التي تملك صلاحية الاطلاع عليها.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable><Pressable onPress={() => router.push("/notifications" as never)} style={({ pressed }) => [styles.accountCard, { marginTop: 10 }, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="notifications-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>مركز الإشعارات</Text><Text style={styles.cardBody}>تحديثات التذاكر والحساب داخل التطبيق.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable><Pressable onPress={() => router.push("/knowledge" as never)} style={({ pressed }) => [styles.accountCard, { marginTop: 10 }, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="book-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>مركز المعرفة</Text><Text style={styles.cardBody}>مقالات وأسئلة شائعة إرشادية مع مصدر وتاريخ تحديث.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable><Pressable onPress={() => router.push("/inquiries" as never)} style={({ pressed }) => [styles.accountCard, { marginTop: 10 }, pressed && styles.pressed]}><View style={styles.iconBox}><Ionicons name="help-buoy-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>مركز الدعم</Text><Text style={styles.cardBody}>أنشئ تذكرة وتابع الردود المرتبطة بطلبك.</Text></View><Ionicons name="chevron-back" size={19} color="#0B5D45" /></Pressable></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>اللغة</Text><View style={styles.card}><View style={styles.copy}><Text style={styles.cardTitle}>لغة الواجهة</Text><Text style={styles.cardBody}>العربية هي اللغة الافتراضية. يمكن تفعيل الإنجليزية واتجاه القراءة LTR للشاشات الداعمة.</Text><View style={styles.roleChoices}><Pressable onPress={() => void setLocale("ar")} style={[styles.roleChoice, locale === "ar" && styles.roleChoiceActive]}><Text style={[styles.roleText, locale === "ar" && styles.roleTextActive]}>العربية</Text></Pressable><Pressable onPress={() => void setLocale("en")} style={[styles.roleChoice, locale === "en" && styles.roleChoiceActive]}><Text style={[styles.roleText, locale === "en" && styles.roleTextActive]}>English</Text></Pressable></View></View><View style={styles.iconBox}><Ionicons name="language-outline" color="#0B5D45" size={22} /></View></View></View>
    {!isAuthenticated && <View style={styles.section}><Text style={styles.sectionTitle}>دور المعاينة المحلي</Text><View style={styles.card}><View style={styles.copy}><Text style={styles.cardTitle}>مساحة الاستخدام</Text><Text style={styles.cardBody}>يعمل هذا الاختيار للمعاينة فقط، ويتوقف تلقائياً عند تسجيل الدخول بحساب فعلي.</Text><View style={styles.roleChoices}>{roles.map((item) => <Pressable key={item.value} onPress={() => void setRole(item.value)} style={({ pressed }) => [styles.roleChoice, role === item.value && styles.roleChoiceActive, pressed && styles.pressed]}><Text style={[styles.roleText, role === item.value && styles.roleTextActive]}>{item.label}</Text></Pressable>)}</View>{role !== "customer" && <Pressable onPress={() => router.push("/operations" as never)} style={({ pressed }) => [styles.operationsButton, pressed && styles.pressed]}><Text style={styles.operationsText}>فتح مساحة التشغيل</Text></Pressable>}</View></View></View>}
    <View style={styles.section}><Text style={styles.sectionTitle}>تنبيهات المواعيد</Text><View style={styles.card}><View style={styles.iconBox}><Ionicons name="notifications-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{permission === "granted" ? "التنبيهات مفعّلة" : "ذكّرني بالمواعيد"}</Text><Text style={styles.cardBody}>{reminderMessage}</Text>{permission !== "granted" && permission !== "unsupported" && <Pressable onPress={enableReminders} style={({ pressed }) => [styles.permissionButton, pressed && styles.pressed]}><Text style={styles.permissionText}>تفعيل الإشعارات</Text></Pressable>}</View></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>الخصوصية</Text><View style={styles.card}><View style={styles.iconBox}><Ionicons name="phone-portrait-outline" color="#0B5D45" size={22} /></View><View style={styles.copy}><Text style={styles.cardTitle}>بياناتك على جهازك</Text><Text style={styles.cardBody}>تُحفَظ بيانات المعاينة محلياً على هذا الجهاز. أبو مشعل منصة مستقلة ولا يتصل بمنصة حكومية.</Text></View></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>عن التطبيق</Text><View style={styles.aboutRow}><Text style={styles.version}>الإصدار 1.0</Text><Text style={styles.cardTitle}>أبو مشعل · متابعة المعاملات والمهام</Text></View></View>
  </ScreenContainer>;
}
const styles = StyleSheet.create({ container: { padding: 20 }, header: { alignItems: "flex-end", marginBottom: 28 }, title: { color: "#17382F", fontSize: 24, fontWeight: "800", writingDirection: "rtl" }, subtitle: { color: "#66756E", fontSize: 13, marginTop: 5, writingDirection: "rtl" }, section: { marginBottom: 26 }, sectionTitle: { color: "#66756E", fontSize: 13, fontWeight: "800", marginBottom: 10, textAlign: "right", writingDirection: "rtl" }, card: { alignItems: "flex-start", backgroundColor: "#FFFFFF", borderColor: "#E1E9E3", borderRadius: 20, borderWidth: 1, flexDirection: "row-reverse", gap: 12, padding: 16 }, accountCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D7E9DB", borderRadius: 20, borderWidth: 1, flexDirection: "row-reverse", gap: 12, padding: 16 }, iconBox: { alignItems: "center", backgroundColor: "#E9F5EC", borderRadius: 12, height: 42, justifyContent: "center", width: 42 }, copy: { alignItems: "flex-end", flex: 1 }, cardTitle: { color: "#17382F", fontSize: 14, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, cardBody: { color: "#66756E", fontSize: 13, lineHeight: 20, marginTop: 5, textAlign: "right", writingDirection: "rtl" }, roleChoices: { flexDirection: "row-reverse", gap: 8, marginTop: 13 }, roleChoice: { backgroundColor: "#FFFFFF", borderColor: "#DCE7DE", borderRadius: 999, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, roleChoiceActive: { backgroundColor: "#E9F5EC", borderColor: "#0B5D45" }, roleText: { color: "#66756E", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, roleTextActive: { color: "#0B5D45" }, operationsButton: { alignSelf: "flex-end", backgroundColor: "#0B5D45", borderRadius: 10, marginTop: 12, paddingHorizontal: 12, paddingVertical: 9 }, operationsText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, permissionButton: { alignSelf: "flex-end", backgroundColor: "#0B5D45", borderRadius: 10, marginTop: 12, paddingHorizontal: 12, paddingVertical: 9 }, permissionText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, aboutRow: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E1E9E3", borderRadius: 18, borderWidth: 1, flexDirection: "row-reverse", justifyContent: "space-between", padding: 16 }, version: { color: "#66756E", fontSize: 12, writingDirection: "rtl" }, pressed: { opacity: 0.72 }, });
