import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { StatusPill } from "@/components/status-pill";
import { useAppRole } from "@/lib/role-provider";
import { isTransactionOverdue } from "@/lib/transactions";
import { useTransactions } from "@/lib/transactions-provider";
import { useWorkspace } from "@/lib/workspace-provider";

export default function OperationsScreen() {
  const router = useRouter();
  const { role } = useAppRole();
  const { transactions, updateStatus } = useTransactions();
  const { tasks, appointments } = useWorkspace();
  const overdueTransactions = transactions.filter((item) => isTransactionOverdue(item));
  const actionRequired = transactions.filter((item) => ["awaiting_customer_documents", "payment_required", "revision_required", "beneficiary_attendance_required"].includes(item.status));
  const openTasks = tasks.filter((task) => task.status !== "completed").length;

  if (role === "customer") return <ScreenContainer style={styles.gated}><Ionicons name="lock-closed-outline" size={34} color="#0B5D45" /><Text style={styles.gatedTitle}>مساحة التشغيل مخصصة للفريق</Text><Text style={styles.gatedText}>من الإعدادات يمكنك تبديل دور المعاينة محلياً إلى موظف أو مشرف لاستعراض هذه المساحة.</Text><Pressable onPress={() => router.push("/(tabs)/settings")} style={styles.gatedButton}><Text style={styles.gatedButtonText}>الذهاب إلى الإعدادات</Text></Pressable></ScreenContainer>;

  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.nav}><Pressable onPress={() => router.back()} style={styles.closeButton}><Ionicons name="close" size={22} color="#17382F" /></Pressable><View style={styles.navCopy}><Text style={styles.brand}>أبو مشعل · {role === "supervisor" ? "المشرف" : "الموظف"}</Text><Text style={styles.title}>مساحة التشغيل</Text></View></View>
    <View style={styles.grid}><Metric icon="layers-outline" label="طلبات نشطة" value={transactions.filter((item) => item.status !== "completed").length} /><Metric icon="alert-circle-outline" label="تحتاج إجراء" value={actionRequired.length} tone="amber" /><Metric icon="time-outline" label="متأخرة" value={overdueTransactions.length} tone="red" /><Metric icon="checkmark-done-outline" label="مهام مفتوحة" value={openTasks} /></View>
    <Text style={styles.sectionTitle}>تحتاج متابعة الآن</Text>
    <View style={styles.list}>{[...overdueTransactions, ...actionRequired].slice(0, 5).map((item) => <View key={item.id} style={styles.card}><View style={styles.cardTop}><StatusPill status={isTransactionOverdue(item) ? "overdue" : item.status} /><Text style={styles.cardTitle}>{item.title}</Text></View><Text style={styles.cardMeta}>{item.agency} · {item.requestNumber || item.reference || "بدون رقم"}</Text><View style={styles.cardBottom}><Pressable onPress={() => router.push({ pathname: "/transaction/[id]", params: { id: item.id } })}><Text style={styles.link}>فتح الطلب</Text></Pressable>{role === "supervisor" && <Pressable onPress={() => void updateStatus(item.id, "under_review", "تمت إعادة الطلب إلى المراجعة من مساحة المشرف.")}><Text style={styles.actionLink}>إعادة للمراجعة</Text></Pressable>}</View></View>)}</View>
    {!overdueTransactions.length && !actionRequired.length && <View style={styles.empty}><Ionicons name="shield-checkmark-outline" size={32} color="#63A987" /><Text style={styles.emptyText}>لا توجد طلبات عاجلة حالياً. راجع المواعيد القادمة أدناه.</Text></View>}
    <Text style={styles.sectionTitle}>المواعيد القادمة</Text>
    <View style={styles.list}>{appointments.slice(0, 3).map((appointment) => <View key={appointment.id} style={styles.card}><Text style={styles.cardTitle}>{appointment.title}</Text><Text style={styles.cardMeta}>{new Date(appointment.startsAt).toLocaleDateString("ar-SA")}</Text></View>)}</View>
    {role === "supervisor" && <Pressable onPress={() => router.push("/reports" as never)} style={styles.reportButton}><Ionicons name="bar-chart-outline" size={19} color="#FFFFFF" /><Text style={styles.reportText}>عرض التقارير التشغيلية</Text></Pressable>}
  </ScrollView></ScreenContainer>;
}
function Metric({ icon, label, value, tone }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: number; tone?: "amber" | "red" }) { return <View style={[styles.metric, tone === "amber" && styles.metricAmber, tone === "red" && styles.metricRed]}><Ionicons name={icon} size={20} color={tone === "amber" ? "#AA6D12" : tone === "red" ? "#B42318" : "#0B5D45"} /><Text style={styles.metricNumber}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34 }, nav: { alignItems: "center", flexDirection: "row-reverse", gap: 12 }, closeButton: { alignItems: "center", backgroundColor: "#F0F4F0", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, navCopy: { alignItems: "flex-end", flex: 1 }, brand: { color: "#0B5D45", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, title: { color: "#17382F", fontSize: 22, fontWeight: "800", writingDirection: "rtl" }, grid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 10, marginTop: 22 }, metric: { backgroundColor: "#F1F8F3", borderColor: "#D9EBDD", borderRadius: 16, borderWidth: 1, minHeight: 112, padding: 13, width: "48.5%" }, metricAmber: { backgroundColor: "#FFF8EC", borderColor: "#F0D9A7" }, metricRed: { backgroundColor: "#FFF1F0", borderColor: "#F3CECB" }, metricNumber: { color: "#17382F", fontSize: 27, fontWeight: "800", marginTop: 8 }, metricLabel: { color: "#66756E", fontSize: 12, marginTop: 3, writingDirection: "rtl" }, sectionTitle: { color: "#344D42", fontSize: 15, fontWeight: "800", marginBottom: 10, marginTop: 26, textAlign: "right", writingDirection: "rtl" }, list: { gap: 10 }, card: { backgroundColor: "#FFFFFF", borderColor: "#E1E9E3", borderRadius: 16, borderWidth: 1, padding: 14 }, cardTop: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, cardTitle: { color: "#17382F", fontSize: 14, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, cardMeta: { color: "#6A7C73", fontSize: 12, marginTop: 6, textAlign: "right", writingDirection: "rtl" }, cardBottom: { flexDirection: "row-reverse", gap: 18, marginTop: 12 }, link: { color: "#0B5D45", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, actionLink: { color: "#AA6D12", fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, reportButton: { alignItems: "center", backgroundColor: "#0B5D45", borderRadius: 14, flexDirection: "row-reverse", gap: 8, justifyContent: "center", marginTop: 20, minHeight: 50 }, reportText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800", writingDirection: "rtl" }, empty: { alignItems: "center", backgroundColor: "#F7FAF8", borderColor: "#E1E9E3", borderRadius: 18, borderStyle: "dashed", borderWidth: 1, padding: 28 }, emptyText: { color: "#66756E", fontSize: 13, lineHeight: 20, marginTop: 8, textAlign: "center", writingDirection: "rtl" }, gated: { alignItems: "center", justifyContent: "center", padding: 28 }, gatedTitle: { color: "#17382F", fontSize: 19, fontWeight: "800", marginTop: 14, writingDirection: "rtl" }, gatedText: { color: "#66756E", fontSize: 13, lineHeight: 21, marginTop: 7, textAlign: "center", writingDirection: "rtl" }, gatedButton: { backgroundColor: "#0B5D45", borderRadius: 14, marginTop: 18, paddingHorizontal: 17, paddingVertical: 12 }, gatedButtonText: { color: "#FFFFFF", fontWeight: "800", writingDirection: "rtl" }, });
